name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and publish to Github package
      run: 
        docker build . --file Dockerfile --tag docker.pkg.github.com/D3n0Duz/helloworld-go/app:${VERSION}
        docker login docker.pkg.github.com --username D3n0Duz --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/D3n0Duz/helloworld-go/app:${VERSION}
        
